

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeZu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

var Client = require('../../client'), constants = Client.constants;

module.exports = Client.sub({
	getShipments: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/orders/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&q={q}&qLimit={qLimit}&includeBin={includeBin}&responseFields={responseFields}'
    }),
	getShipment: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/orders/{shipmentId}?draft={draft}&includeBin={includeBin}&responseFields={responseFields}'
	})
});
